### ISSUE TITLE
typo in RData URI

### ISSUE THREAD

**Issue by ahmadswaid** [SiLeBAT/fskml#9]
The FSKML Library uses the URI 
http://purl.org/NET/mediatypes/x-RData  as a key to retrieve the Files of type RData
In one of the fskx file (20180619194821_Listeria_model_Risk_Characterization_Product.fskx) 
anotherURI http://purl.org/NET/mediatypes/text/x-RData was used. 
@miguelalba  Please correct this typo in the library.

**Comment by miguelalba** [comment]
Thanks. Fixed in d9168ef.
